name: GitHub Actions Demo
run-name: CI pipeline
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.1

      - uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.20.x

      - name: Install tools
        run: make install-tools

      - run: make lint